### PR TITLE
Domain blocks

### LINKED ISSUE #4: Add domain blocks and automate updating
Domain blocks can be uploaded at https://docs.joinmastodon.org/methods/admin/domain_blocks/. We can start by adding the downloaded existing blocks to this repo, then automating their upload. It would maybe be nice to store this as CSV or something locally, so it can be browsed easily, rather than as JSON.

### PR DESCRIPTION
**Pull request by pikesley**
We consider the [`domain_blocks.csv`](domain_blocks.csv) file at the root of this repo to be the canonical list. This role takes that list and hits the [`/api/v1/admin/domain_blocks`](https://docs.joinmastodon.org/methods/admin/domain_blocks/#create) endpoint for each domain. This operation is idempotent - if a domain is already blocked the API returns a `422 Unprocessable Entity`, which we just absorb. 

MDN [says](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422) about a `422`, `Warning: The client should not repeat this request without modification.`, but meh.

Thanks to [symroe](https://github.com/symroe) for [pointing me towards this Ansible module](https://mastodon.me.uk/@symroe/109551531403249940)

This PR resolves #4.

### CODE REVIEW

**Review by Floppy — APPROVED** [review]
Looks great, I just need to set up the token before I merge. Thanks!

**Comment by Floppy** [comment]
Looks like I cocked up the tokens again...

**Comment by Floppy** [comment]
I don't actually have an `admin:write:blocks` option on the token, I've given it `read:blocks write:blocks admin:write` instead.

**Comment by pikesley** [comment]
https://docs.joinmastodon.org/methods/admin/domain_blocks/#create `¯\_(ツ)_/¯`

**Comment by Floppy** [comment]
Huh, weird. OK, I'll explore further. That seems to not match the token UI.

**Comment by pikesley** [comment]
I definitely had that scope available in my local Mastodon instance (which is now broken)

**Comment by pikesley** [comment]
Screenshot 2022-12-22 at 16 45 13

**Comment by pikesley** [comment]
I think this might be me being an idiot again tbh

**Comment by Floppy** [comment]
wait a goddamn minute... this is what I have:

Screenshot 2022-12-22 at 18 00 15

**Comment by Floppy** [comment]
What version are you running? We're on 4.0.2, I don't understand how I don't have the same options as you.

**Comment by pikesley** [comment]
That's all you have? What?

**Comment by pikesley** [comment]
Screenshot 2022-12-22 at 18 06 53
 
4.0.2

**Comment by pikesley** [comment]
Do we need to get on a call?

**Comment by Floppy** [comment]
I'll ask the fediverse....

**Pull request merged**
